# ---------------------------------------------
# ⚠️ AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
# Source: backend/db/data_models/__init__.py
# Generated by: backend/db/scripts/generate_crud_schemas.py
# Time: 2025-07-02 23:01:22 PDT
# ---------------------------------------------

from datetime import datetime
from typing import Any, Optional
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class AssetsCreate(BaseModel):
    user_id: UUID
    asset_key_original: str
    asset_key_display: str
    asset_key_llm: str
    metadata_: Optional[dict[str, Any]] = Field(alias="metadata")


class AssetsUpdate(BaseModel):
    user_id: Optional[UUID] = None
    asset_key_original: Optional[str] = None
    asset_key_display: Optional[str] = None
    asset_key_llm: Optional[str] = None
    metadata_: Optional[dict[str, Any]] = Field(default=None, alias="metadata")


class AssetsRead(BaseModel):
    id: UUID
    user_id: UUID
    asset_key_original: str
    asset_key_display: str
    asset_key_llm: str
    metadata_: Optional[dict[str, Any]] = Field(alias="metadata")
    created_at: Optional[datetime]
    model_config = ConfigDict(from_attributes=True)


class JobsCreate(BaseModel):
    job_type: str
    status: str
    input_payload: Optional[dict[str, Any]]
    result_payload: Optional[dict[str, Any]]
    error_message: Optional[str]
    user_id: Optional[UUID]
    photobook_id: Optional[UUID]
    started_at: Optional[datetime]
    completed_at: Optional[datetime]


class JobsUpdate(BaseModel):
    job_type: Optional[str] = None
    status: Optional[str] = None
    input_payload: Optional[dict[str, Any]] = None
    result_payload: Optional[dict[str, Any]] = None
    error_message: Optional[str] = None
    user_id: Optional[UUID] = None
    photobook_id: Optional[UUID] = None
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None


class JobsRead(BaseModel):
    id: UUID
    job_type: str
    status: str
    input_payload: Optional[dict[str, Any]]
    result_payload: Optional[dict[str, Any]]
    error_message: Optional[str]
    user_id: Optional[UUID]
    photobook_id: Optional[UUID]
    created_at: Optional[datetime]
    started_at: Optional[datetime]
    completed_at: Optional[datetime]
    model_config = ConfigDict(from_attributes=True)


class PagesCreate(BaseModel):
    photobook_id: Optional[UUID]
    page_number: int
    user_message: Optional[str]
    layout: Optional[str]


class PagesUpdate(BaseModel):
    photobook_id: Optional[UUID] = None
    page_number: Optional[int] = None
    user_message: Optional[str] = None
    layout: Optional[str] = None


class PagesRead(BaseModel):
    id: UUID
    photobook_id: Optional[UUID]
    page_number: int
    user_message: Optional[str]
    layout: Optional[str]
    created_at: Optional[datetime]
    model_config = ConfigDict(from_attributes=True)


class PagesAssetsRelCreate(BaseModel):
    page_id: Optional[UUID]
    asset_id: Optional[UUID]
    order_index: Optional[int]
    caption: Optional[str]


class PagesAssetsRelUpdate(BaseModel):
    page_id: Optional[UUID] = None
    asset_id: Optional[UUID] = None
    order_index: Optional[int] = None
    caption: Optional[str] = None


class PagesAssetsRelRead(BaseModel):
    id: UUID
    page_id: Optional[UUID]
    asset_id: Optional[UUID]
    order_index: Optional[int]
    caption: Optional[str]
    model_config = ConfigDict(from_attributes=True)


class PhotobooksCreate(BaseModel):
    user_id: UUID
    title: str
    caption: Optional[str]
    theme: Optional[str]
    status: Optional[str]


class PhotobooksUpdate(BaseModel):
    user_id: Optional[UUID] = None
    title: Optional[str] = None
    caption: Optional[str] = None
    theme: Optional[str] = None
    status: Optional[str] = None


class PhotobooksRead(BaseModel):
    id: UUID
    user_id: UUID
    title: str
    caption: Optional[str]
    theme: Optional[str]
    status: Optional[str]
    created_at: Optional[datetime]
    updated_at: Optional[datetime]
    model_config = ConfigDict(from_attributes=True)
