# ---------------------------------------------
# ⚠️ AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
# Source: backend/db/schemas/__init__.py, backend/db/data_models/__init__.py
# Generated by: backend/db/scripts/generate_sqlmodel_from_sql.py
# Time: 2025-07-02 23:01:22 PDT
# ---------------------------------------------

from datetime import datetime, timezone
from typing import Any, Optional
from uuid import UUID, uuid4

from sqlalchemy.dialects.postgresql import JSON
from sqlmodel import Field, SQLModel


class Assets(SQLModel, table=True):
    id: UUID = Field(primary_key=True, default_factory=uuid4)
    user_id: UUID
    asset_key_original: str
    asset_key_display: str
    asset_key_llm: str
    metadata_: Optional[dict[str, Any]] = Field(
        default=None, alias="metadata", sa_type=JSON
    )
    created_at: Optional[datetime] = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )


class Jobs(SQLModel, table=True):
    id: UUID = Field(primary_key=True, default_factory=uuid4)
    job_type: str
    status: str
    input_payload: Optional[dict[str, Any]] = Field(default=None, sa_type=JSON)
    result_payload: Optional[dict[str, Any]] = Field(default=None, sa_type=JSON)
    error_message: Optional[str] = Field(default=None)
    user_id: Optional[UUID] = Field(default=None)
    photobook_id: Optional[UUID] = Field(default=None)
    created_at: Optional[datetime] = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    started_at: Optional[datetime] = Field(default=None)
    completed_at: Optional[datetime] = Field(default=None)


class Pages(SQLModel, table=True):
    id: UUID = Field(primary_key=True, default_factory=uuid4)
    photobook_id: Optional[UUID] = Field(default=None)
    page_number: int
    user_message: Optional[str] = Field(default=None)
    layout: Optional[str] = Field(default=None)
    created_at: Optional[datetime] = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )


class PagesAssetsRel(SQLModel, table=True):
    id: UUID = Field(primary_key=True, default_factory=uuid4)
    page_id: Optional[UUID] = Field(default=None)
    asset_id: Optional[UUID] = Field(default=None)
    order_index: Optional[int] = Field(default=None)
    caption: Optional[str] = Field(default=None)


class Photobooks(SQLModel, table=True):
    id: UUID = Field(primary_key=True, default_factory=uuid4)
    user_id: UUID
    title: str
    caption: Optional[str] = Field(default=None)
    theme: Optional[str] = Field(default=None)
    status: Optional[str]
    created_at: Optional[datetime] = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    updated_at: Optional[datetime] = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
